server:
  port: 3344
spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:zzyybs/springcloud-config.git #GitHub上面的git仓库名字
#          uri: git@github.com:abc908159305/springcloud-config.git
          uri: https://github.com/abc908159305/springcloud-config.git
          ####搜索目录
          search-paths:
            - springcloud-config
          username: abc908159305
          password: 205212780y
#          force-pull: true
      ####读取分支
      label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

